### ISSUE TITLE
LSNS Element in Jacob1's mod

### ISSUE THREAD

**Issue by git123hub** [jacob1/The-Powder-Toy#13]

**Comment by jacob1** [comment]
None of the new elements are present in my mod yet. I want to increase the element limit in my mod before adding them. 6 elements is a lot to add at once, and 3 of the elements in the snapshots are still unfinished.

**Comment by jacob1** [comment]
Oh, I forgot you opened this ... but yes, fixed in ea3de19f6bf8f3e004bc68ab16916b2d82faa17a

**Comment by git123hub** [comment]
Add to Jacob1's mod:
https://github.com/jacob1/The-Powder-Toy/blob/c++/src/simulation/elements/LSNS.cpp
