### ISSUE TITLE
ctrl+backspace highlights words

### ISSUE THREAD

**Issue by ghost** [jacob1/The-Powder-Toy#18]
In various text fields (tested with comments, but I believe it applies to the upload form too), pressing ctrl+backspace in the middle of the text will give some characters (seems to be equal in length to deleted word) in front of the carat the highlighted effect.

Pressing backspace (with control or not) or any character will not delete them, but pressing delete will. They can also be copied with ctrl+C.

**Comment by jacob1** [comment]
Those both use the "old" textboxes. Maybe I can fix it anyway. The "new" textboxes (like in the profile edit ui) have more features.
