### ISSUE TITLE
Large screen not updating mouse area

### ISSUE THREAD

**Issue by kdrag0n** [jacob1/The-Powder-Toy#2]
1. Start your mod
2. Make sure it's small screen
3. Settings → Large screen ON
4. Close Settings
5. Move mouse around

Linux Linux Mint 16 (Ubuntu 14.04) 64 bit
V28.1

**Comment by jacob1** [comment]
Well that's slightly weird / embarrassing >_>. My screen is too small for double size, but i'll fix it in the next version.

**Comment by kdrag0n** [comment]
It seems to work in 29.1, that's why I closed it... Or maybe 1920x1200 works, used to have 1680x1050...

Maybe b9016bd6f37456e8b6800493a59448842d4b44d2 fixed it...

**Comment by jacob1** [comment]
oh. I'm still using 29.0 >_<

**Comment by jacob1** [comment]
Seems to be a Linux issue (affects tpt too), I couldn't find a simple fix that doesn't use opengl but deleting the window and making a new one works well :P.

**Comment by kdrag0n** [comment]
works on TPT 89.2 :o

**Comment by jacob1** [comment]
if it does happen, it's only when you are in scale 1 and then change to scale 2, once you restart tpt it won't ever happen again so it's weird ...

Also I can't reproduce it any more in the latest tpt source >_<, but it definitely happens in the old 89.2 build I have. I just decided to do nothing for official tpt and just leave it fixed like this in my mod.
