### ISSUE TITLE
Large window prevents resizeable window

### ISSUE THREAD

**Issue by ghost** [jacob1/The-Powder-Toy#24]
Enable "Large window" option. Now enabling "resizeable window" has no effect.

Easiest fix would just be to automatically disable the former at the same time, I presume.

**Comment by jacob1** [comment]
I can't reproduce this, on Linux or on Windows. No matter how "large window" is checked, resizable window still always works. Can you give more exact steps you did to get a bug to appear?

**Comment by ghost** [comment]
I see the problem now. I can resize, but the resize targets are further in/smaller than I expect. It seems to be only 3 pixels wide while most windows get 6, and along the innermost edge of normal. So when I move outside the corner where I would expect a handle, it doesn't appear.

But sometimes it doesn't happen?

**Comment by jacob1** [comment]
Yep, you are right. It also seems random to me. It's definitely an SDL issue but I can maybe try googling.

Just be glad you aren't on Linux. The edges have only one pixel you can resize at, and the corners are maybe 2x2 or 3x3 max.

**Comment by jacob1** [comment]
Do you also notice that the window border changes size when you toggle "resizable window"? The top border shrinks for some reason and the whole window shifts. When this happens, that's when the bug occurs.

It fixes itself if you resize it just one pixel, it's very weird.

I didn't see any issues about it on the sdl bug tracker. And when I compile it in visual studio it doesn't happen (even though my mod is compiled with msvc on windows anyway ...)

**Comment by ghost** [comment]
I don't know about border shrinkage, but it definitely shifts up and to the left regularly.

**Comment by jacob1** [comment]
As of commit fa6a8efbbef77f3fc6815570bfa0ef7498899178 , I'm now recreating the window when toggling resizable window. This should fix the problem.
