### ISSUE TITLE
No longer reacts to mouse releases outside window

### ISSUE THREAD

**Issue by ghost** [jacob1/The-Powder-Toy#28]
Press a mouse button and drag it outside the window. If you release the button afterwards, the program will continue to act as if it is being held down until brought back into the window area.

This used to work fine. Now doing things like drawing a rectangle to the edge of the screen appears unresponsive.

**Comment by jacob1** [comment]
Yeah, I noticed this right after the update but haven't done a 2nd update yet.

I did fix this already too: https://github.com/jacob1/The-Powder-Toy/commit/e29902bbb60186deca1216152ed9870632bff42e
But I haven't tested it. This bug only happens on Windows.
