### ISSUE TITLE
Saving bug

### ISSUE THREAD

**Issue by KBDeveloper** [jacob1/The-Powder-Toy#3]
Pasting a trademarked symbol(™) into a sign,
a)looks weird in-game
b)makes it so it errors when trying to save/publish and crashes the game if you try to save/publish it again
-Windows 8.1 Pro Edition x64, Custom Built Computer

**Comment by jacob1** [comment]
why are you trying to paste unicode into a sign? ... the TPT font doesn't support that :P. I can try and prevent pasting weird characters into signs I guess ...
