### ISSUE TITLE
Element search menu does not work after recent update

### ISSUE THREAD

**Issue by Drackonic** [jacob1/The-Powder-Toy#31]
The element search, the one accessed by pressing E, appears but can not be interacted with at all and must be closed by pressing escape as even the dismiss button does not work.

Here is a video that will hopefully demonstrate the issue: https://www.youtube.com/watch?v=dDiktJ-RzJw

**Comment by jacob1** [comment]
Weird.

You're the 2nd person to report this. I just checked and apparently it only happens on Windows, not on Linux. I definitely would have noticed if it was broken on Linux because I almost exclusively use element search to select things.

**Comment by Drackonic** [comment]
How strange, I wonder why it only occurs on windows.

**Comment by jacob1** [comment]
This bug was so dumb, I have no idea why it only just started happening. Either way, I tested and it's fixed now. I'll update my mod hopefully tomorrow ... as long as I also release TPT 95.0 tomorrow. If not, it will hopefully be Monday or Tuesday.
