### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by AJRed** [jacob1/The-Powder-Toy#39]
I'm trying to compile Jacobs mod for Arch linux and I keep getting an error about curl_mime having a conflicting declaration between the game's curl.h and my system's

Console output:

scons: Reading SConscript files ...
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking if 64 bit... (cached) yes
Adding 64 bit compile flags
Checking for C library SDL2... (cached) yes
Checking for C header file SDL2/SDL.h... (cached) yes
Checking for C library lua5.1... (cached) yes
Checking for C library dl... (cached) yes
Checking for C library fftw3f... (cached) yes
Checking for C library bz2... (cached) yes
Checking for C header file bzlib.h... (cached) yes
Checking for C library z... (cached) yes
Checking for C library curl... (cached) yes
Checking for C library pthread... (cached) yes
Checking for C library m... (cached) yes
Checking for C library X11... (cached) yes
Checking for C library rt... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/src/interface.o -c -std=c++17 -Wno-invalid-offsetof -msse -msse2 -D_64BIT -D_REENTRANT -DLUA_R_INCL -DLIN -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -Ibuild/src -Isrc -Ibuild/includes -Iincludes -I/usr/include/SDL2 -I/usr/include/lua5.1 src/interface.cpp
g++ -o build/src/game/Request.o -c -std=c++17 -Wno-invalid-offsetof -msse -msse2 -D_64BIT -D_REENTRANT -DLUA_R_INCL -DLIN -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -Ibuild/src -Isrc -Ibuild/includes -Iincludes -I/usr/include/SDL2 -I/usr/include/lua5.1 src/game/Request.cpp
In file included from src/game/Request.cpp:4:
/usr/include/curl/curl.h:2365:16: error: using typedef-name ‘curl_mime’ after ‘struct’
 2365 | typedef struct curl_mime      curl_mime;      /* Mime context. */
      |                ^~~~~~~~~
In file included from src/game/Request.cpp:1:
src/game/Request.h:16:28: note: ‘curl_mime’ has a previous declaration here
   16 | typedef struct curl_mime_s curl_mime;
      |                            ^~~~~~~~~
/usr/include/curl/curl.h:2365:31: error: conflicting declaration ‘typedef int curl_mime’
 2365 | typedef struct curl_mime      curl_mime;      /* Mime context. */
      |                               ^~~~~~~~~
src/game/Request.h:16:28: note: previous declaration as ‘typedef struct curl_mime_s curl_mime’
   16 | typedef struct curl_mime_s curl_mime;
      |                            ^~~~~~~~~
src/game/Request.cpp: In member function ‘void Request::Start()’:
src/game/Request.cpp:246:40: warning: ‘CURLOPT_PROTOCOLS’ is deprecated: since 7.85.0. Use CURLOPT_PROTOCOLS_STR [-Wdeprecated-declarations]
  246 |                 curl_easy_setopt(easy, CURLOPT_PROTOCOLS, CURLPROTO_HTTPS);
      |                                        ^~~~~~~~~~~~~~~~~
/usr/include/curl/curl.h:1749:3: note: declared here
 1749 |   CURLOPTDEPRECATED(CURLOPT_PROTOCOLS, CURLOPTTYPE_LONG, 181,
      |   ^~~~~~~~~~~~~~~~~
src/game/Request.cpp:247:40: warning: ‘CURLOPT_REDIR_PROTOCOLS’ is deprecated: since 7.85.0. Use CURLOPT_REDIR_PROTOCOLS_STR [-Wdeprecated-declarations]
  247 |                 curl_easy_setopt(easy, CURLOPT_REDIR_PROTOCOLS, CURLPROTO_HTTPS);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/curl/curl.h:1755:3: note: declared here
 1755 |   CURLOPTDEPRECATED(CURLOPT_REDIR_PROTOCOLS, CURLOPTTYPE_LONG, 182,
      |   ^~~~~~~~~~~~~~~~~
scons: *** [build/src/game/Request.o] Error 1
scons: building terminated because of errors.
strip: 'build/powder64': No such file

**Comment by jacob1** [comment]
In Request.h, edit near the top to change curl_mime_s to curl_mime in two places:

-struct curl_mime_s;
+struct curl_mime;
 struct curl_httppost;
-typedef struct curl_mime_s curl_mime;
+typedef struct curl_mime curl_mime;

This is a horrible hack, all to save a few milliseconds of compile time. curl changed their structures slightly in some recent version, but my build server still uses an older version of curl. I hope to address it in the future some day.

**Comment by AJRed** [comment]
Worked perfectly; thank you for your help. I figured it had something to do with that but I'm not familiar enough with C++ to have figured it out myself.
