### ISSUE TITLE
Hardcoded button position

### ISSUE THREAD

**Issue by donat-b** [jacob1/The-Powder-Toy#7]
![window](https://cloud.githubusercontent.com/assets/1835559/11981533/9a9792be-a9b4-11e5-886d-4b72aeeeb6da.png)

I've tried looking for the code responsible for it, but kind of gave up. ¯_(ツ)_/¯
Can you please fix it?

**Comment by jacob1** [comment]
lol ...

Well those buttons are actually lua scripts, in this directory: https://github.com/jacob1/The-Powder-Toy/tree/c%2B%2B/src/luascripts . You might need to edit scriptmanager.lua and multiplayer.lua, then run the .sh scripts.

The main repo for the script manager is https://github.com/cracker64/TPT-Script-Manager
And the main repo for multiplayer is https://github.com/cracker64/tptmp

I think I already fixed the hardcoded position for the script manager, but I haven't updated it in my mod. I guess I can look into updating it and then fixing multiplayer too.

**Comment by jacob1** [comment]
Both of the buttons should be fixed now. I updated the script manager to the newer version, and finally fixed tptmp.

**Comment by donat-b** [comment]
Woah. Thanks a lot!
