### ISSUE TITLE
Liquid hydrogen

### ISSUE THREAD

**Issue by donat-b** [jacob1/The-Powder-Toy#8]
It has always struck me as odd that oxygen condenses while hydrogen doesn't.
Hydrogen has slightly different boiling point and density which might be useful sometimes.
Even better, if liquid hydrogen can be transformed into metallic form.
What do you think about adding this element?

**Comment by jacob1** [comment]
Dunno, i'm not really a big fan of adding new elements :P. This has been suggested before but I wouldn't want to break things by adding a new state to an existing TPT element.
