### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Sciguy429** [jacob1/The-Powder-Toy#9]
I'm experiencing a weird issue when trying to build for mobile

<pre>
$ scons.py --nomod --touchui
scons: Reading SConscript files ...
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking if 64 bit... (cached) no
Adding 32 bit compile flags
Checking for C library mingw32... (cached) yes
Checking for C library ws2_32... (cached) yes
Checking for C library SDLmain... (cached) yes
Checking for C library SDL... (cached) yes
Checking for C header file SDL/SDL.h... (cached) yes
Checking for C library lua5.1... (cached) yes
Checking for C header file lua5.1/lua.h... (cached) yes
Checking for C library fftw3f... (cached) yes
Checking for C library bz2... (cached) yes
Checking for C header file bzlib.h... (cached) yes
Checking for C library pthread... (cached) yes
Checking for C library m... (cached) yes
Checking for C library gnurx... (cached) no
Checking for C library regex... (cached) yes
Checking for C library gdi32... (cached) yes
Checking for C library winmm... (cached) yes
Checking for C library dxguid... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build\src\BSON.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\BSON.cpp
g++ -o build\src\air.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\air.cpp
g++ -o build\src\benchmark.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\benchmark.cpp
g++ -o build\src\cJSON.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\cJSON.cpp
g++ -o build\src\console.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\console.cpp
g++ -o build\src\fontdata.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\fontdata.cpp
g++ -o build\src\graphics.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\graphics.cpp
g++ -o build\src\hmap.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\hmap.cpp
g++ -o build\src\http.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\http.cpp
g++ -o build\src\hud.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\hud.cpp
g++ -o build\src\imagedata.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\imagedata.cpp
g++ -o build\src\interface.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\interface.cpp
g++ -o build\src\luabit.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\luabit.cpp
g++ -o build\src\luaconsole.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\luaconsole.cpp
g++ -o build\src\luascriptinterface.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\luascriptinterface.cpp
g++ -o build\src\main.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\main.cpp
g++ -o build\src\md5.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\md5.cpp
g++ -o build\src\misc.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\misc.cpp
g++ -o build\src\powder.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\powder.cpp
g++ -o build\src\save.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\save.cpp
g++ -o build\src\update.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\update.cpp
g++ -o build\src\common\Platform.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\common\Platform.cpp
g++ -o build\src\common\Probability.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\common\Probability.cpp
g++ -o build\src\game\Brush.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\game\Brush.cpp
g++ -o build\src\game\Download.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\game\Download.cpp
g++ -o build\src\game\DownloadManager.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\game\DownloadManager.cpp
g++ -o build\src\game\Favorite.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\game\Favorite.cpp
g++ -o build\src\game\Menus.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\game\Menus.cpp
g++ -o build\src\game\Sign.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\game\Sign.cpp
g++ -o build\src\game\ToolTip.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\game\ToolTip.cpp
g++ -o build\src\graphics\Pixel.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\graphics\Pixel.cpp
g++ -o build\src\graphics\VideoBuffer.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\graphics\VideoBuffer.cpp
g++ -o build\src\interface\Button.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\interface\Button.cpp
g++ -o build\src\interface\Component.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\interface\Component.cpp
g++ -o build\src\interface\Engine.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\interface\Engine.cpp
g++ -o build\src\interface\Label.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\interface\Label.cpp
g++ -o build\src\interface\ScrollWindow.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\interface\ScrollWindow.cpp
g++ -o build\src\interface\Textbox.o -c -std=gnu++98 -Wno-invalid-offsetof -msse -msse2 -O3 -ftree-vectorize -funsafe-math-optimizations -ffast-math -fomit-frame-pointer -funsafe-loop-optimizations -w -DWIN -D_WIN32_WINNT=0x0501 -DX86 -DX86_SSE -DX86_SSE2 -DGRAVFFT -DLUACONSOLE -DNOMOD -DTOUCHUI -Ibuild\src -Isrc -Ibuild\includes -Iincludes src\interface\Textbox.cpp
=====
src\interface\Textbox.cpp: In member function 'virtual void Textbox::OnFocus()':
src\interface\Textbox.cpp:277:35: error: 'memcpy' was not declared in this scope
  memcpy(buffer, text.c_str(), 1024);
                                   ^

=====
scons: *** [build\src\interface\Textbox.o] Error 1
scons: building terminated because of errors.
strip: 'build/Powder.exe': No such file
</pre>

It builds normally with `scons.py` without any options but refuses to compile for android :cry:

**Comment by jacob1** [comment]
Very convenient, I fixed this already while on vacation! I had no internet so it wasn't pushed. I will push it now.

I made some far-reaching changes to lots of files though, it fixes all the warnings (so that I can use --wall now), and does some other stuff.

**Comment by jacob1** [comment]
Fixed in dcc75f3d8177168061fbc32cc6f7e221a36362a7

**Comment by Sciguy429** [comment]
OK im gonna go test this now :D thanks Jacob
